<?php
/**
 * JetEngine Profile Builder Flat URLs
 *
 * Removes base path from JetEngine Profile Builder subpage URLs.
 * Converts /console/academy/ to /academy/ while maintaining functionality.
 *
 * @package    RCP_Content_Filter
 * @subpackage Includes
 * @since      1.0.56
 */

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class RCF_JetEngine_Flat_URLs
 *
 * Implements flat URL structure for JetEngine Profile Builder subpages.
 */
class RCF_JetEngine_Flat_URLs {

	/**
	 * Singleton instance
	 *
	 * @var RCF_JetEngine_Flat_URLs|null
	 */
	private static ?self $instance = null;

	/**
	 * Base page ID (e.g., the "Console" page)
	 *
	 * @var int
	 */
	private int $base_page_id = 0;

	/**
	 * Base page slug (e.g., "console")
	 *
	 * @var string
	 */
	private string $base_slug = '';

	/**
	 * Get singleton instance
	 *
	 * @return self
	 */
	public static function get_instance(): self {
		if ( null === self::$instance ) {
			self::$instance = new self();
		}
		return self::$instance;
	}

	/**
	 * Constructor
	 */
	private function __construct() {
		// Only initialize if JetEngine is active
		if ( ! $this->is_jetengine_active() ) {
			return;
		}

		// Hook into JetEngine Profile Builder
		add_filter( 'jet-engine/profile-builder/rewrite-rules', array( $this, 'add_flat_rewrite_rules' ), 10, 2 );
		add_filter( 'jet-engine/profile-builder/subpage-url', array( $this, 'remove_base_from_url' ), 10, 3 );

		// Flush rewrite rules on activation (do this sparingly)
		add_action( 'admin_init', array( $this, 'maybe_flush_rewrite_rules' ) );
	}

	/**
	 * Check if JetEngine is active and Profile Builder is available
	 *
	 * @return bool
	 */
	private function is_jetengine_active(): bool {
		return class_exists( 'Jet_Engine' ) && function_exists( 'jet_engine' );
	}

	/**
	 * Add flat rewrite rules for JetEngine subpages
	 *
	 * This filter allows WordPress to recognize top-level URLs like /academy/
	 * and internally route them to the correct JetEngine Profile Builder subpage.
	 *
	 * @param array $rules  Existing rewrite rules.
	 * @param array $config JetEngine Profile Builder configuration.
	 * @return array Modified rewrite rules.
	 */
	public function add_flat_rewrite_rules( array $rules, array $config ): array {
		// Ensure we have configuration data
		if ( empty( $config ) || empty( $config['account_page_id'] ) ) {
			return $rules;
		}

		// Get base page information
		$this->base_page_id = absint( $config['account_page_id'] );
		$base_page          = get_post( $this->base_page_id );

		if ( ! $base_page ) {
			return $rules;
		}

		$this->base_slug = $base_page->post_name;

		// Get all subpages from configuration
		$subpages = ! empty( $config['subpages'] ) ? $config['subpages'] : array();

		if ( empty( $subpages ) ) {
			return $rules;
		}

		// Add flat URL rewrite rules for each subpage
		foreach ( $subpages as $subpage ) {
			if ( empty( $subpage['slug'] ) ) {
				continue;
			}

			$subpage_slug = sanitize_title( $subpage['slug'] );

			// Add rule for flat URL: /academy/ → /console/academy/
			// This tells WordPress to internally route /academy/ to the correct handler
			$rules[ "^{$subpage_slug}/?$" ]          = "index.php?page_id={$this->base_page_id}&jet_account_page={$subpage_slug}";
			$rules[ "^{$subpage_slug}/page/([0-9]+)/?$" ] = "index.php?page_id={$this->base_page_id}&jet_account_page={$subpage_slug}&paged=\$matches[1]";
		}

		return $rules;
	}

	/**
	 * Remove base path from JetEngine Profile Builder subpage URLs
	 *
	 * This filter modifies the URLs generated by the Profile Menu widget
	 * to use flat structure (e.g., /academy/ instead of /console/academy/).
	 *
	 * @param string $url          The original URL with base path.
	 * @param array  $subpage      Subpage configuration.
	 * @param array  $config       Full Profile Builder configuration.
	 * @return string Modified URL without base path.
	 */
	public function remove_base_from_url( string $url, array $subpage, array $config ): string {
		// Ensure we have configuration
		if ( empty( $config['account_page_id'] ) || empty( $subpage['slug'] ) ) {
			return $url;
		}

		// Get base page information if not already set
		if ( empty( $this->base_page_id ) ) {
			$this->base_page_id = absint( $config['account_page_id'] );
			$base_page          = get_post( $this->base_page_id );

			if ( $base_page ) {
				$this->base_slug = $base_page->post_name;
			}
		}

		// If we don't have a base slug, return original URL
		if ( empty( $this->base_slug ) ) {
			return $url;
		}

		$subpage_slug = sanitize_title( $subpage['slug'] );

		// Remove the base slug from the URL
		// Convert: https://example.com/console/academy/ → https://example.com/academy/
		$pattern = '#/' . preg_quote( $this->base_slug, '#' ) . '/' . preg_quote( $subpage_slug, '#' ) . '/?#';
		$url     = preg_replace( $pattern, '/' . $subpage_slug . '/', $url );

		return $url;
	}

	/**
	 * Flush rewrite rules if needed
	 *
	 * Only flushes once per plugin version update to avoid performance issues.
	 *
	 * @return void
	 */
	public function maybe_flush_rewrite_rules(): void {
		// Check if we've already flushed for this version
		$flushed_version = get_option( 'rcf_jetengine_rewrite_flushed' );

		if ( $flushed_version === RCP_FILTER_VERSION ) {
			return;
		}

		// Flush rewrite rules
		flush_rewrite_rules();

		// Mark as flushed for this version
		update_option( 'rcf_jetengine_rewrite_flushed', RCP_FILTER_VERSION );
	}

	/**
	 * Get current base page ID
	 *
	 * @return int
	 */
	public function get_base_page_id(): int {
		return $this->base_page_id;
	}

	/**
	 * Get current base slug
	 *
	 * @return string
	 */
	public function get_base_slug(): string {
		return $this->base_slug;
	}
}

// Initialize
add_action( 'plugins_loaded', array( RCF_JetEngine_Flat_URLs::class, 'get_instance' ), 20 );
